os: Visual Studio 2015

branches:
  only:
    - master

clone_folder: C:\projects\pyfribidi

environment:
  global:
    REPO_DIR: C:\projects\pyfribidi
    TWINE_USERNAME: MrRLBitBucket
    TWINE_PASSWORD:
      secure: 7XgI2S6O+eY0YtqvwbIk0F5Ism+kJq7vn1S1oSKlx08=
    CITOOLS_USER: rl-wheelbuilder
    CITOOLS_PASSWORD:
      secure: xbq9uLuFeus1N1x8xSF9f5kAYXY4lkvU4UveYwgcMkM=
    FIRST: 27
    LAST: 38-x64
    RLCACHE: windows/reportlab

  matrix:
    - PYVER: 27
      ARCH: X86

    - PYVER: 27-x64
      ARCH: AMD64

    - PYVER: 35
      ARCH: X86

    - PYVER: 35-x64
      ARCH: AMD64

    - PYVER: 36
      ARCH: X86

    - PYVER: 36-x64
      ARCH: AMD64

    - PYVER: 37
      ARCH: X86

    - PYVER: 37-x64
      ARCH: AMD64

    - PYVER: 38
      ARCH: X86

    - PYVER: 38-x64
      ARCH: AMD64

matrix:
  fast_finish: true

install:
  - cmd: echo "=============================== Python%PYVER% install FIRST='%FIRST%' LAST='%LAST%'"
  - "SET PATH=C:\\Python%PYVER%;c:\\Python%PYVER%\\scripts;%PATH%"
  - "SET SETUP_VERBOSE=1"
  - ps: |
        $py_exe = "C:\Python${env:PYVER}\Python.exe"
        if ( -Not ([System.IO.File]::Exists($py_exe)) ) {
            if ( -Not ([System.IO.File]::Exists("C:\projects\install_python.ps1")) ) {
                Write-Host "Fetching install_python.ps1" -ForegroundColor Yellow
                curl -o C:\projects\install_python.ps1 https://www.reportlab.com/ftp/install_python.ps1
                if ( -Not ([System.IO.File]::Exists("C:\projects\install_python.ps1")) ) {
                    Write-Host "C:\projects\install_python.ps1 was not fetched" -ForegroundColor Red
                    exit 1
                }
            }
            C:\projects\install_python.ps1
        }
  - cmd: echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat"
  - cmd: c:\Python37-x64\python.exe -mvirtualenv c:\projects\myenv
  - cmd: c:\projects\myenv\scripts\python.exe -mpip install pip setuptools wheel -U
  - cmd: c:\projects\myenv\scripts\pip.exe --version
  - cmd: c:\projects\myenv\scripts\pip.exe install meson ninja
  - cmd: c:\projects\myenv\scripts\pip.exe install https://hg.reportlab.com/hg-public/rl-ci-tools/archive/tip.tar.gz
  - cmd: if not exist C:\Python%PYVER%\python.exe ( echo "!!!!!!!!!!!!!!!!!!!!!!! C:\Python%PYVER%\python.exe not found" && exit 1 )
  - cmd: if not exist C:\Python%PYVER%\scripts\pip.exe ( echo "!!!!!!!!!!!!!!!!!!!!!!! C:\Python%PYVER%\scripts\pip.exe not found" && exit 1 )
  - cmd: git clone https://github.com/fribidi/fribidi c:\projects\fribidi-src

build_script:
  - if "%PYVER%" == "%FIRST%" c:\projects\myenv\scripts\python.exe -mrl_ci_tools clear-cache %RLCACHE%
  - cmd: if not exist C:\Python%PYVER%\python.exe ( echo "!!!!!!!!!!!!!!!!!!!!!!! C:\Python%PYVER%\python.exe not found" && exit 1 )
  - cmd: if not exist C:\Python%PYVER%\scripts\pip.exe ( echo "!!!!!!!!!!!!!!!!!!!!!!! C:\Python%PYVER%\scripts\pip.exe not found" && exit 1 )
  - cmd: cd c:\projects\fribidi-src
  - cmd: echo %PATH%
  - cmd: echo SETLOCAL >> doit.bat
  - cmd: echo echo ON >> doit.bat
  #- cmd: echo c:\projects\myenv\scripts\activate >> doit.bat
  - cmd: echo SET PATH=C:\projects\myenv;c:\projects\myenv\scripts;%PATH% >> doit.bat
  - cmd: echo call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %ARCH% >> doit.bat
  - cmd: echo if exist build c:\projects\myenv\scripts\python.exe -c"import shutils;shutils.rmtree('build',ignore_errors=True)" >> doit.bat
  - cmd: echo c:\projects\myenv\scripts\meson.exe -Ddocs=false --backend=ninja --default-library=both build >> doit.bat
  - cmd: echo c:\projects\myenv\scripts\ninja.exe -C build test >> doit.bat
  - cmd: echo c:\projects\myenv\scripts\python.exe -c"import glob;print(repr(glob.glob('c:/projects/fribidi-src/**/*.h',recursive=True)))" >> doit.bat
  - cmd: echo curl -s https://github.com/mattn/gntp-send/blob/master/include/msinttypes/stdint.h > lib\stdint.h
  - cmd: echo echo OFF >> doit.bat
  - cmd: echo ENDLOCAL >> doit.bat
  - call doit.bat
  - cmd: echo %PATH%
  #- cmd: c:\projects\myenv\scripts\activate
  #- call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %ARCH%
  #- cmd: if exist build c:\projects\myenv\scripts\python.exe -c"import shutils;shutils.rmtree('build',ignore_errors=True)"
  #- cmd: c:\projects\myenv\scripts\meson.exe -Ddocs=false --backend=ninja --default-library=both build
  #- cmd: c:\projects\myenv\scripts\ninja.exe -C build test
  #- cmd: c:\projects\myenv\scripts\deactivate
  - cmd: cd c:\projects\pyfribidi
  - cmd: c:\Python%PYVER%\python.exe -mpip install -U pip setuptools wheel
  - cmd: c:\Python%PYVER%\scripts\pip.exe --version
  - cmd: c:\Python%PYVER%\python.exe -W ignore setup.py bdist_wheel

on_success:
  - echo "=============================== Python%PYVER% on_success"
  - if "%PYVER%" == "%LAST%" c:\projects\myenv\scripts\python.exe -mrl_ci_tools env
  - c:\projects\myenv\scripts\python.exe -mrl_ci_tools upload-caches --subdir=%RLCACHE% --verbosity=1 dist/*.whl
  - if "%PYVER%" == "%LAST%" c:\projects\myenv\scripts\python.exe -mrl_ci_tools email --subject="+++++ APPVEYOR %APPVEYOR_PROJECT_NAME% build succeeded" --faddr=rl-wheelbuilder --body="see https://www.reportlab.com/pypi/cache-info/%RLCACHE%/*/"

on_failure:
  - c:\projects\myenv\scripts\python.exe -mrl_ci_tools email --subject="!!!!! APPVEYOR %APPVEYOR_PROJECT_NAME% build failed" --faddr=rl-wheelbuilder --body="see https://ci.appveyor.com/project/MrRLBitBucket/%PROJECT_NAME%/history"

test_script:
  - echo "=============================== Python%PYVER% TEST START"
  - c:\Python37-x64\python.exe -mvirtualenv -p C:\Python%PYVER%\python.exe c:\projects\testenv
  - c:\projects\testenv\scripts\python.exe -mpip install -U pip setuptools wheel
  - c:\projects\testenv\scripts\pip.exe --version
  - c:\projects\testenv\scripts\pip.exe install --cache-dir=dist --find-links file:dist --pre pyfribidi
  #- c:\projects\myenv\scripts\python.exe -mrl_ci_tools info --recur c:\projects\testenv\Lib\site-packages
  #- c:\projects\myenv\scripts\python.exe -mrl_ci_tools info --recur c:\projects\testenv\Lib\site-packages\reportlab\fonts
  - c:\projects\testenv\Scripts\python.exe src\test_pyfribidi.py
  - echo "=============================== Python%PYVER% TEST END"

#artifacts:
#  - path: 'mydist\*.whl'
#    name: wheel

#deploy_script:
  #- ps: if ($env:APPVEYOR_REPO_TAG -eq $TRUE) { pip install twine; twine upload dist/* }
  #- c:\projects\myenv\scripts\python -mrl_ci_tools upload-packages --verbosity=1 mydist\*.whl

deploy: off
