rm -f "fribidi-0.19.6\bin\fribidi-benchmark.exe
rm -f "fribidi-0.19.6\bin\fribidi-benchmark.obj
rm -f "fribidi-0.19.6\bin\fribidi-bidi-types.exe
rm -f "fribidi-0.19.6\bin\fribidi-bidi-types.obj
rm -f "fribidi-0.19.6\bin\fribidi-caprtl2utf8.exe
rm -f "fribidi-0.19.6\bin\fribidi-caprtl2utf8.obj
rm -f "fribidi-0.19.6\bin\fribidi-main.obj
rm -f "fribidi-0.19.6\bin\fribidi.dll
rm -f "fribidi-0.19.6\bin\fribidi.exe
rm -f "fribidi-0.19.6\bin\fribidi.lib
rm -f "fribidi-0.19.6\bin\getopt.obj
rm -f "fribidi-0.19.6\bin\getopt1.obj
rm -f "fribidi-0.19.6\bin\vc70.idb
rm -f "fribidi-0.19.6\gen.tab\gen-arabic-shaping-tab.exe
rm -f "fribidi-0.19.6\gen.tab\gen-arabic-shaping-tab.obj
rm -f "fribidi-0.19.6\gen.tab\gen-bidi-type-tab.exe
rm -f "fribidi-0.19.6\gen.tab\gen-bidi-type-tab.obj
rm -f "fribidi-0.19.6\gen.tab\gen-joining-type-tab.exe
rm -f "fribidi-0.19.6\gen.tab\gen-joining-type-tab.obj
rm -f "fribidi-0.19.6\gen.tab\gen-mirroring-tab.exe
rm -f "fribidi-0.19.6\gen.tab\gen-mirroring-tab.obj
rm -f "fribidi-0.19.6\gen.tab\gen-unicode-version.exe
rm -f "fribidi-0.19.6\gen.tab\gen-unicode-version.obj
rm -f "fribidi-0.19.6\gen.tab\packtab.obj
rm -f "fribidi-0.19.6\gen.tab\vc70.idb
rm -f "fribidi-0.19.6\lib\fribidi-arabic.obj
rm -f "fribidi-0.19.6\lib\fribidi-bidi-types.obj
rm -f "fribidi-0.19.6\lib\fribidi-bidi.obj
rm -f "fribidi-0.19.6\lib\fribidi-char-sets-cap-rtl.obj
rm -f "fribidi-0.19.6\lib\fribidi-char-sets-cp1255.obj
rm -f "fribidi-0.19.6\lib\fribidi-char-sets-cp1256.obj
rm -f "fribidi-0.19.6\lib\fribidi-char-sets-iso8859-6.obj
rm -f "fribidi-0.19.6\lib\fribidi-char-sets-iso8859-8.obj
rm -f "fribidi-0.19.6\lib\fribidi-char-sets-utf8.obj
rm -f "fribidi-0.19.6\lib\fribidi-char-sets.obj
rm -f "fribidi-0.19.6\lib\fribidi-deprecated.obj
rm -f "fribidi-0.19.6\lib\fribidi-joining-types.obj
rm -f "fribidi-0.19.6\lib\fribidi-joining.obj
rm -f "fribidi-0.19.6\lib\fribidi-mem.obj
rm -f "fribidi-0.19.6\lib\fribidi-mirroring.obj
rm -f "fribidi-0.19.6\lib\fribidi-run.obj
rm -f "fribidi-0.19.6\lib\fribidi-shape.obj
rm -f "fribidi-0.19.6\lib\fribidi.dll
rm -f "fribidi-0.19.6\lib\fribidi.exp
rm -f "fribidi-0.19.6\lib\fribidi.lib
rm -f "fribidi-0.19.6\lib\fribidi.obj
rm -f "fribidi-0.19.6\lib\vc70.idb
rm -f "fribidi-0.19.6\test\test_CapRTL_explicit.output
rm -f "fribidi-0.19.6\test\test_CapRTL_implicit.output
rm -f "fribidi-0.19.6\test\test_ISO8859-8_hebrew.output
rm -f "fribidi-0.19.6\test\test_UTF-8_persian.output
rm -f "fribidi-0.19.6\test\test_UTF-8_reordernsm.output
